#!/bin/sh

php /home/darling/Git/PHPJsonUtilities/tests/integration/TestCanEncodeAndDecodeAClassesThatDefinesAPropertyThatAcceptsAnArrayThatMayContainObjectInstances.php
php /home/darling/Git/PHPJsonUtilities/tests/integration/TestCanEncodeAndDecodeAMultiDimensionalArray.php
php /home/darling/Git/PHPJsonUtilities/tests/integration/TestCanEncodeAndDecodeANumericallyIndexedArray.php
php /home/darling/Git/PHPJsonUtilities/tests/integration/TestCanEncodeAndDecodeASingleDimensionalArray.php
php /home/darling/Git/PHPJsonUtilities/tests/integration/TestCanEncodeAndDecodeAnArray.php
php /home/darling/Git/PHPJsonUtilities/tests/integration/TestCanEncodeAndDecodeAnAssociativelyIndexedArray.php
